/*constants for all actions in the app*/

// constants for categories actions
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY_REMOTE = "GET_CATEGORY_REMOTE";
export const GET_CATEGORY_START = "GET_CATEGORY_START";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

// constants for products action
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_REMOTE_PRODUCT = "GET_REMOTE_PRODUCT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

// constants for user action
export const LOGIN_REMOTE_USER = "LOGIN_REMOTE_USER";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_REMOTE_USER = "REGISTER_REMOTE_USER"
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCESS = "REGISTER_USER_SUCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";


// Constants for shopping cart action
export const GET_CART_USER_REMOTE = "GET_CART_USER";
export const GET_CART_USER_START = "GET_CART_USER_START";
export const GET_CART_USER_SUCCESS = "GET_CART_USER_SUCCESS";
export const GET_CART_USER_ERROR = "GET_CART_USER_ERROR";

export const ADD_PRODUCT_TO_CART_REMOTE = "ADD_PRODUCT_TO_CART_REMOTE";
export const ADD_PRODUCT_TO_CART_START = "ADD_PRODUCT_TO_CART_START";
export const ADD_PRODUCT_TO_CART_SUCESS = "ADD_PRODUCT_TO_CART_SUCESS";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR";

export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";


